spring:
  #  thymeleaf: # Thymeleaf
  #    cache: false
  #    mode: HTML
  #    encoding: UTF-8
  #    prefix: file:src/main/resources/templates/
  #  resources: # Static resources
  #    static-locations: file:src/main/resources/static/
  #    cache:
  #      period: 0

  # JPA
  # spring.jpa.hibernate.ddl-auto=update
  jpa:
    hibernate:
      ddl-auto: update
  # Console access
  h2:
    console:
      enabled: true
      path: /h2

  # Datasource
  datasource:
    #url: jdbc:h2:file:~/test
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  devtools:
    livereload:
      enabled:true